"""empty message

Revision ID: 75a0cd77af97
Revises: 3bc2f5d19084
Create Date: 2022-06-05 22:04:39.283485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a0cd77af97'
down_revision = '3bc2f5d19084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_pic', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_pic')
    # ### end Alembic commands ###
