"""empty message

Revision ID: ba7e259ad664
Revises: 75a0cd77af97
Create Date: 2022-06-05 22:06:31.836594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7e259ad664'
down_revision = '75a0cd77af97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_pic', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_pic')
    # ### end Alembic commands ###
